-- schema
CREATE SCHEMA D24;

-- table
CREATE TABLE D24.selection (
    id_selection  INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Tour          INTEGER,
    Choix         INTEGER,
    Équipe        VARCHAR (500),
    Joueur        VARCHAR (500),
    Poste         VARCHAR (500),
    Université    VARCHAR (500),
    Conférence    VARCHAR (500),
    Poste_nom     VARCHAR (500),
    Groupe_poste  VARCHAR (500),
    Groupe_conf   VARCHAR (500)
    );

-- insert
--=("insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values ('"&A2&"', '"&B2&"', '"&C2&"', '"&D2&"', '"&E2&"', '"&F2&"', '"&G2&"')");
=("insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values ('"&A2&"', '"&B2&"', '"&C2&"', '"&D2&"', '"&E2&"', '"&F2&"', '"&G2&"')")
--
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 1,'Chicago Bears', 'Caleb Williams', 'QB', 'USC', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 2,'Washington Commanders', 'Jayden Daniels', 'QB', 'LSU', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 3,'New England Patriots', 'Drake Maye', 'QB', 'North Carolina', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 4,'Arizona Cardinals', 'Marvin Harrison Jr.', 'WR', 'Ohio State', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 5,'Los Angeles Chargers', 'Joe Alt', 'OT', 'Notre Dame', 'Ind. (FBS)');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 6,'New York Giants', 'Malik Nabers', 'WR', 'LSU', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 7,'Tennessee Titans', 'JC Latham', 'OT', 'Alabama', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 8,'Atlanta Falcons', 'Michael Penix Jr.', 'QB', 'Washington', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 9,'Chicago Bears', 'Rome Odunze', 'WR', 'Washington', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 10, 'Minnesota Vikings', 'J. J. McCarthy', 'QB', 'Michigan', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 11, 'New York Jets', 'Olu Fashanu', 'OT', 'Penn State', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 12, 'Denver Broncos', 'Bo Nix', 'QB', 'Oregon', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 13, 'Las Vegas Raiders', 'Brock Bowers', 'TE', 'Georgia', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 14, 'New Orleans Saints', 'Taliese Fuaga', 'OT', 'Oregon State', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 15, 'Indianapolis Colts', 'Laiatu Latu', 'DE', 'UCLA', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 16, 'Seattle Seahawks', 'Byron Murphy II', 'DT', 'Texas', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 17, 'Minnesota Vikings', 'Dallas Turner', 'DE', 'Alabama', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 18, 'Cincinnati Bengals', 'Amarius Mims', 'OT', 'Georgia', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 19, 'Los Angeles Rams', 'Jared Verse', 'DE', 'Florida State', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 20, 'Pittsburgh Steelers', 'Troy Fautanu', 'OT', 'Washington', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 21, 'Miami Dolphins', 'Chop Robinson', 'DE', 'Penn State', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 22, 'Philadelphia Eagles', 'Quinyon Mitchell', 'CB', 'Toledo', 'MAC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 23, 'Jacksonville Jaguars', 'Brian Thomas Jr.', 'WR', 'LSU', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 24, 'Detroit Lions', 'Terrion Arnold', 'CB', 'Alabama', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 25, 'Green Bay Packers', 'Jordan Morgan', 'OT', 'Arizona', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 26, 'Tampa Bay Buccaneers', 'Graham Barton', 'C', 'Duke', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 27, 'Arizona Cardinals', 'Darius Robinson', 'DE', 'Missouri', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 28, 'Kansas City Chiefs', 'Xavier Worthy', 'WR', 'Texas', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 29, 'Dallas Cowboys', 'Tyler Guyton', 'OT', 'Oklahoma', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 30, 'Baltimore Ravens', 'Nate Wiggins', 'CB', 'Clemson', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 31, 'San Francisco 49ers', 'Ricky Pearsall', 'WR', 'Florida', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (1, 32, 'Carolina Panthers', 'Xavier Legette', 'WR', 'South Carolina', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 33, 'Buffalo Bills', 'Keon Coleman', 'WR', 'Florida State', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 34, 'Los Angeles Chargers', 'Ladd McConkey', 'WR', 'Georgia', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 35, 'Atlanta Falcons', 'Ruke Orhorhoro', 'DT', 'Clemson', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 36, 'Washington Commanders', 'Johnny Newton', 'DT', 'Illinois', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 37, 'New England Patriots', 'Ja''Lynn Polk', 'WR', 'Washington', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 38, 'Tennessee Titans', 'T''Vondre Sweat', 'DT', 'Texas', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 39, 'Los Angeles Rams', 'Braden Fiske', 'DT', 'Florida State', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 40, 'Philadelphia Eagles', 'Cooper DeJean', 'CB', 'Iowa', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 41, 'New Orleans Saints', 'Kool-Aid McKinstry', 'CB', 'Alabama', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 42, 'Houston Texans', 'Kamari Lassiter', 'CB', 'Georgia', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 43, 'Arizona Cardinals', 'Max Melton', 'CB', 'Rutgers', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 44, 'Las Vegas Raiders', 'Jackson Powers-Johnson', 'OG', 'Oregon', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 45, 'Green Bay Packers', 'Edgerrin Cooper', 'LB', 'Texas A&M', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 46, 'Carolina Panthers', 'Jonathon Brooks', 'RB', 'Texas', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 47, 'New York Giants', 'Tyler Nubin', 'S', 'Minnesota', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 48, 'Jacksonville Jaguars', 'Maason Smith', 'DT', 'LSU', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 49, 'Cincinnati Bengals', 'Kris Jenkins', 'DT', 'Michigan', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 50, 'Washington Commanders', 'Mike Sainristil', 'CB', 'Michigan', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 51, 'Pittsburgh Steelers', 'Zach Frazier', 'C', 'West Virginia', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 52, 'Indianapolis Colts', 'Adonai Mitchell', 'WR', 'Texas', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 53, 'Washington Commanders', 'Ben Sinnott', 'TE', 'Kansas State', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 54, 'Cleveland Browns', 'Michael Hall Jr.', 'DT', 'Ohio State', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 55, 'Miami Dolphins', 'Patrick Paul', 'OT', 'Houston', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 56, 'Dallas Cowboys', 'Marshawn Kneeland', 'DE', 'Western Michigan', 'MAC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 57, 'Tampa Bay Buccaneers', 'Chris Braswell', 'DE', 'Alabama', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 58, 'Green Bay Packers', 'Javon Bullard', 'S', 'Georgia', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 59, 'Houston Texans', 'Blake Fisher', 'OT', 'Notre Dame', 'Ind. (FBS)');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 60, 'Buffalo Bills', 'Cole Bishop', 'S', 'Utah', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 61, 'Detroit Lions', 'Ennis Rakestraw Jr.', 'CB', 'Missouri', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 62, 'Baltimore Ravens', 'Roger Rosengarten', 'OT', 'Washington', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 63, 'Kansas City Chiefs', 'Kingsley Suamataia', 'OT', 'BYU', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (2, 64, 'San Francisco 49ers', 'Renardo Green', 'CB', 'Florida State', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 65, 'New York Jets', 'Malachi Corley', 'WR', 'Western Kentucky', 'CUSA');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 66, 'Arizona Cardinals', 'Trey Benson', 'RB', 'Florida State', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 67, 'Washington Commanders', 'Brandon Coleman', 'OT', 'TCU', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 68, 'New England Patriots', 'Caedan Wallace', 'OT', 'Penn State', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 69, 'Los Angeles Chargers', 'Junior Colson', 'LB', 'Michigan', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 70, 'New York Giants', 'Andru Phillips', 'CB', 'Kentucky', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 71, 'Arizona Cardinals', 'Isaiah Adams', 'OG', 'Illinois', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 72, 'Carolina Panthers', 'Trevin Wallace', 'LB', 'Kentucky', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 73, 'Dallas Cowboys', 'Cooper Beebe', 'OG', 'Kansas State', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 74, 'Atlanta Falcons', 'Bralen Trice', 'OLB', 'Washington', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 75, 'Chicago Bears', 'Kiran Amegadjie', 'OT', 'Yale', 'Ivy');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 76, 'Denver Broncos', 'Jonah Elliss', 'DE', 'Utah', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 77, 'Las Vegas Raiders', 'Delmar Glaze', 'OT', 'Maryland', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 78, 'Houston Texans', 'Calen Bullock', 'S', 'USC', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 79, 'Indianapolis Colts', 'Matt Goncalves', 'OT', 'Pittsburgh', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 80, 'Cincinnati Bengals', 'Jermaine Burton', 'WR', 'Alabama', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 81, 'Seattle Seahawks', 'Christian Haynes', 'OG', 'UConn', 'Ind. (FBS)');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 82, 'Arizona Cardinals', 'Tip Reiman', 'TE', 'Illinois', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 83, 'Los Angeles Rams', 'Blake Corum', 'RB', 'Michigan', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 84, 'Pittsburgh Steelers', 'Roman Wilson', 'WR', 'Michigan', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 85, 'Cleveland Browns', 'Zak Zinter', 'OG', 'Michigan', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 86, 'San Francisco 49ers', 'Dominick Puni', 'OG', 'Kansas', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 87, 'Dallas Cowboys', 'Marist Liufau', 'LB', 'Notre Dame', 'Ind. (FBS)');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 88, 'Green Bay Packers', 'MarShawn Lloyd', 'RB', 'USC', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 89, 'Tampa Bay Buccaneers', 'Tykee Smith', 'S', 'Georgia', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 90, 'Arizona Cardinals', 'Elijah Jones', 'CB', 'Boston College', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 91, 'Green Bay Packers', 'Ty''Ron Hopper', 'LB', 'Missouri', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 92, 'Tampa Bay Buccaneers', 'Jalen McMillan', 'WR', 'Washington', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 93, 'Baltimore Ravens', 'Adisa Isaac', 'DE', 'Penn State', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 94, 'Philadelphia Eagles', 'Jalyx Hunt', 'DE', 'Houston Christian', 'Southland');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 95, 'Buffalo Bills', 'DeWayne Carter', 'DT', 'Duke', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 96, 'Jacksonville Jaguars', 'Jarrian Jones', 'CB', 'Florida State', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 97, 'Cincinnati Bengals', 'McKinnley Jackson', 'DT', 'Texas A&M', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 98, 'Pittsburgh Steelers', 'Payton Wilson', 'LB', 'NC State', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 99, 'Los Angeles Rams', 'Kamren Kinchens', 'S', 'Miami (FL)', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (3, 100, 'Washington Commanders', 'Luke McCaffrey', 'WR', 'Rice', 'The American');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 101, 'Carolina Panthers', 'Ja''Tavion Sanders', 'TE', 'Texas', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 102, 'Denver Broncos', 'Troy Franklin', 'WR', 'Oregon', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 103, 'New England Patriots', 'Layden Robinson', 'OG', 'Texas A&M', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 104, 'Arizona Cardinals', 'Dadrion Taylor-Demerson', 'S', 'Texas Tech', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 105, 'Los Angeles Chargers', 'Justin Eboigbe', 'DT', 'Alabama', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 106, 'Tennessee Titans', 'Cedric Gray', 'LB', 'North Carolina', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 107, 'New York Giants', 'Theo Johnson', 'TE', 'Penn State', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 108, 'Minnesota Vikings', 'Khyree Jackson', 'CB', 'Oregon', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 109, 'Atlanta Falcons', 'Brandon Dorlus', 'DT', 'Oregon', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 110, 'New England Patriots', 'Javon Baker', 'WR', 'UCF', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 111, 'Green Bay Packers', 'Evan Williams', 'S', 'Oregon', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 112, 'Las Vegas Raiders', 'Decamerion Richardson', 'CB', 'Mississippi State', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 113, 'Baltimore Ravens', 'Devontez Walker', 'WR', 'North Carolina', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 114, 'Jacksonville Jaguars', 'Javon Foster', 'OT', 'Missouri', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 115, 'Cincinnati Bengals', 'Erick All', 'TE', 'Iowa', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 116, 'Jacksonville Jaguars', 'Jordan Jefferson', 'DT', 'LSU', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 117, 'Indianapolis Colts', 'Tanor Bortolini', 'C', 'Wisconsin', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 118, 'Seattle Seahawks', 'Tyrice Knight', 'LB', 'UTEP', 'CUSA');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 119, 'Pittsburgh Steelers', 'Mason McCormick', 'OG', 'South Dakota State', 'MVFC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 120, 'Miami Dolphins', 'Jaylen Wright', 'RB', 'Tennessee', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 121, 'Seattle Seahawks', 'AJ Barner', 'TE', 'Michigan', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 122, 'Chicago Bears', 'Tory Taylor', 'P', 'Iowa', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 123, 'Houston Texans', 'Cade Stover', 'TE', 'Ohio State', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 124, 'San Francisco 49ers', 'Malik Mustapha', 'S', 'Wake Forest', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 125, 'Tampa Bay Buccaneers', 'Bucky Irving', 'RB', 'Oregon', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 126, 'Detroit Lions', 'Giovanni Manu', 'OT', 'British Columbia', 'CWUAA');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 127, 'Philadelphia Eagles', 'Will Shipley', 'RB', 'Clemson', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 128, 'Buffalo Bills', 'Ray Davis', 'RB', 'Kentucky', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 129, 'San Francisco 49ers', 'Isaac Guerendo', 'RB', 'Louisville', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 130, 'Baltimore Ravens', 'T. J. Tampa', 'CB', 'Iowa State', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 131, 'Kansas City Chiefs', 'Jared Wiley', 'TE', 'TCU', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 132, 'Detroit Lions', 'Sione Vaki', 'RB', 'Utah', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 133, 'Kansas City Chiefs', 'Jaden Hicks', 'S', 'Washington State', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 134, 'New York Jets', 'Braelon Allen', 'RB', 'Wisconsin', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (4, 135, 'San Francisco 49ers', 'Jacob Cowing', 'WR', 'Arizona', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 136, 'Seattle Seahawks', 'Nehemiah Pritchett', 'CB', 'Auburn', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 137, 'Los Angeles Chargers', 'Tarheeb Still', 'CB', 'Maryland', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 138, 'Arizona Cardinals', 'Xavier Thomas', 'DE', 'Clemson', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 139, 'Washington Commanders', 'Jordan Magee', 'LB', 'Temple', 'The American');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 140, 'Los Angeles Chargers', 'Cam Hart', 'CB', 'Notre Dame', 'Ind. (FBS)');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 141, 'Buffalo Bills', 'Sedrick Van Pran-Granger', 'C', 'Georgia', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 142, 'Indianapolis Colts', 'Anthony Gould', 'WR', 'Oregon State', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 143, 'Atlanta Falcons', 'JD Bertrand', 'LB', 'Notre Dame', 'Ind. (FBS)');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 144, 'Chicago Bears', 'Austin Booker', 'DE', 'Kansas', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 145, 'Denver Broncos', 'Kris Abrams-Draine', 'CB', 'Missouri', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 146, 'Tennessee Titans', 'Jarvis Brownlee Jr.', 'CB', 'Louisville', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 147, 'Denver Broncos', 'Audric Estimé', 'RB', 'Notre Dame', 'Ind. (FBS)');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 148, 'Las Vegas Raiders', 'Tommy Eichenberg', 'LB', 'Ohio State', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 149, 'Cincinnati Bengals', 'Josh Newton', 'CB', 'TCU', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 150, 'New Orleans Saints', 'Spencer Rattler', 'QB', 'South Carolina', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 151, 'Indianapolis Colts', 'Jaylon Carlies', 'S', 'Missouri', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 152, 'Philadelphia Eagles', 'Ainias Smith', 'WR', 'Texas A&M', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 153, 'Jacksonville Jaguars', 'Deantre Prince', 'CB', 'Ole Miss', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 154, 'Los Angeles Rams', 'Brennan Jackson', 'DE', 'Washington State', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 155, 'Philadelphia Eagles', 'Jeremiah Trotter Jr.', 'LB', 'Clemson', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 156, 'Cleveland Browns', 'Jamari Thrash', 'WR', 'Louisville', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 157, 'Carolina Panthers', 'Chau Smith-Wade', 'CB', 'Washington State', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 158, 'Miami Dolphins', 'Mohamed Kamara', 'DE', 'Colorado State', 'MW');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 159, 'Kansas City Chiefs', 'Hunter Nourzad', 'C', 'Penn State', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 160, 'Buffalo Bills', 'Edefuan Ulofoshio', 'LB', 'Washington', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 161, 'Washington Commanders', 'Dominique Hampton', 'S', 'Washington', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 162, 'Arizona Cardinals', 'Christian Jones', 'OT', 'Texas', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 163, 'Green Bay Packers', 'Jacob Monk', 'C', 'Duke', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 164, 'Indianapolis Colts', 'Jaylin Simpson', 'S', 'Auburn', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 165, 'Baltimore Ravens', 'Rasheen Ali', 'RB', 'Marshall', 'Sun Belt');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 166, 'New York Giants', 'Tyrone Tracy Jr.', 'RB', 'Purdue', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 167, 'Jacksonville Jaguars', 'Keilan Robinson', 'RB', 'Texas', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 168, 'Buffalo Bills', 'Javon Solomon', 'DE', 'Troy', 'Sun Belt');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 169, 'Green Bay Packers', 'Kitan Oladapo', 'S', 'Oregon State', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 170, 'New Orleans Saints', 'Bub Means', 'WR', 'Pittsburgh', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 171, 'New York Jets', 'Jordan Travis', 'QB', 'Florida State', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 172, 'Philadelphia Eagles', 'Trevor Keegan', 'OG', 'Michigan', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 173, 'New York Jets', 'Isaiah Davis', 'RB', 'South Dakota State', 'MVFC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 174, 'Dallas Cowboys', 'Caelen Carson', 'CB', 'Wake Forest', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 175, 'New Orleans Saints', 'Jaylan Ford', 'LB', 'Texas', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (5, 176, 'New York Jets', 'Qwan''tez Stiggers', 'CB', 'Toronto Argonauts', 'CFL');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 177, 'Minnesota Vikings', 'Walter Rouse', 'OT', 'Oklahoma', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 178, 'Pittsburgh Steelers', 'Logan Lee', 'DT', 'Iowa', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 179, 'Seattle Seahawks', 'Sataoa Laumea', 'OG', 'Utah', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 180, 'New England Patriots', 'Marcellas Dial', 'CB', 'South Carolina', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 181, 'Los Angeles Chargers', 'Kimani Vidal', 'RB', 'Troy', 'Sun Belt');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 182, 'Tennessee Titans', 'Jha''Quan Jackson', 'WR', 'Tulane', 'The American');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 183, 'New York Giants', 'Darius Muasau', 'LB', 'UCLA', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 184, 'Miami Dolphins', 'Malik Washington', 'WR', 'Virginia', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 185, 'Philadelphia Eagles', 'Johnny Wilson', 'WR', 'Florida State', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 186, 'Atlanta Falcons', 'Jase McClellan', 'RB', 'Alabama', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 187, 'Atlanta Falcons', 'Casey Washington', 'WR', 'Illinois', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 188, 'Houston Texans', 'Jamal Hill', 'LB', 'Oregon', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 189, 'Detroit Lions', 'Mekhi Wingo', 'DT', 'LSU', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 190, 'Philadelphia Eagles', 'Dylan McMahon', 'C', 'NC State', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 191, 'Arizona Cardinals', 'Tejhaun Palmer', 'WR', 'UAB', 'The American');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 192, 'Seattle Seahawks', 'D. J. James', 'CB', 'Auburn', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 193, 'New England Patriots', 'Joe Milton', 'QB', 'Tennessee', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 194, 'Cincinnati Bengals', 'Tanner McLachlan', 'TE', 'Arizona', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 195, 'Pittsburgh Steelers', 'Ryan Watts', 'CB', 'Texas', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 196, 'Los Angeles Rams', 'Tyler Davis', 'DT', 'Clemson', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 197, 'Atlanta Falcons', 'Zion Logue', 'DT', 'Georgia', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 198, 'Miami Dolphins', 'Patrick McMorris', 'S', 'California', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 199, 'New Orleans Saints', 'Khristian Boyd', 'DT', 'Northern Iowa', 'MVFC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 200, 'Carolina Panthers', 'Jaden Crumedy', 'DT', 'Mississippi State', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 201, 'Indianapolis Colts', 'Micah Abraham', 'CB', 'Marshall', 'Sun Belt');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 202, 'Green Bay Packers', 'Travis Glover', 'OT', 'Georgia State', 'Sun Belt');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 203, 'Minnesota Vikings', 'Will Reichard', 'K', 'Alabama', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 204, 'Buffalo Bills', 'Tylan Grable', 'OT', 'UCF', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 205, 'Houston Texans', 'Jawhar Jordan', 'RB', 'Louisville', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 206, 'Cleveland Browns', 'Nathaniel Watson', 'LB', 'Mississippi State', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 207, 'Seattle Seahawks', 'Michael Jerrell', 'OT', 'Findlay', 'G-MAC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 208, 'Las Vegas Raiders', 'Dylan Laube', 'RB', 'New Hampshire', 'CAA');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 209, 'Los Angeles Rams', 'Joshua Karty', 'K', 'Stanford', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 210, 'Detroit Lions', 'Christian Mahogany', 'OG', 'Boston College', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 211, 'Kansas City Chiefs', 'Kamal Hadden', 'CB', 'Tennessee', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 212, 'Jacksonville Jaguars', 'Cam Little', 'K', 'Arkansas', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 213, 'Los Angeles Rams', 'Jordan Whittington', 'WR', 'Texas', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 214, 'Cincinnati Bengals', 'Cedric Johnson', 'DE', 'Ole Miss', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 215, 'San Francisco 49ers', 'Jarrett Kingston', 'OG', 'USC', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 216, 'Dallas Cowboys', 'Ryan Flournoy', 'WR', 'Southeast Missouri State', 'BSC–OVC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 217, 'Los Angeles Rams', 'Beaux Limmer', 'C', 'Arkansas', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 218, 'Baltimore Ravens', 'Devin Leary', 'QB', 'Kentucky', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 219, 'Buffalo Bills', 'Daequan Hardy', 'CB', 'Penn State', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (6, 220, 'Tampa Bay Buccaneers', 'Elijah Klein', 'OG', 'UTEP', 'CUSA');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 221, 'Buffalo Bills', 'Travis Clayton', 'OT', 'Rugby union', 'English');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 222, 'Washington Commanders', 'Javontae Jean-Baptiste', 'DE', 'Notre Dame', 'Ind. (FBS)');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 223, 'Las Vegas Raiders', 'Trey Taylor', 'S', 'Air Force', 'MW');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 224, 'Cincinnati Bengals', 'Daijahn Anthony', 'S', 'Ole Miss', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 225, 'Los Angeles Chargers', 'Brenden Rice', 'WR', 'USC', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 226, 'Arizona Cardinals', 'Jaden Davis', 'CB', 'Miami (FL)', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 227, 'Cleveland Browns', 'Myles Harden', 'CB', 'South Dakota', 'MVFC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 228, 'Baltimore Ravens', 'Nick Samac', 'C', 'Michigan State', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 229, 'Las Vegas Raiders', 'M. J. Devonshire', 'CB', 'Pittsburgh', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 230, 'Minnesota Vikings', 'Michael Jurgens', 'C', 'Wake Forest', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 231, 'New England Patriots', 'Jaheim Bell', 'TE', 'Florida State', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 232, 'Minnesota Vikings', 'Levi Drake Rodriguez', 'DT', 'Texas A&M–Commerce', 'Southland');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 233, 'Dallas Cowboys', 'Nathan Thomas', 'OT', 'Louisiana', 'Sun Belt');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 234, 'Indianapolis Colts', 'Jonah Laulu', 'DT', 'Oklahoma', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 235, 'Denver Broncos', 'Devaughn Vele', 'WR', 'Utah', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 236, 'Jacksonville Jaguars', 'Myles Cole', 'DE', 'Texas Tech', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 237, 'Cincinnati Bengals', 'Matt Lee', 'C', 'Miami (FL)', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 238, 'Houston Texans', 'Solomon Byrd', 'DE', 'USC', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 239, 'New Orleans Saints', 'Josiah Ezirim', 'OT', 'Eastern Kentucky', 'UAC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 240, 'Carolina Panthers', 'Michael Barrett', 'LB', 'Michigan', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 241, 'Miami Dolphins', 'Tahj Washington', 'WR', 'USC', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 242, 'Tennessee Titans', 'James Williams', 'S', 'Miami (FL)', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 243, 'Cleveland Browns', 'Jowon Briggs', 'DT', 'Cincinnati', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 244, 'Dallas Cowboys', 'Justin Rogers', 'DT', 'Auburn', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 245, 'Green Bay Packers', 'Michael Pratt', 'QB', 'Tulane', 'The American');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 246, 'Tampa Bay Buccaneers', 'Devin Culp', 'TE', 'Washington', 'Pac-12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 247, 'Houston Texans', 'Marcus Harris', 'DT', 'Auburn', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 248, 'Kansas City Chiefs', 'C. J. Hanson', 'OG', 'Holy Cross', 'Patriot');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 249, 'Houston Texans', 'LaDarius Henderson', 'OG', 'Michigan', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 250, 'Baltimore Ravens', 'Sanoussi Kane', 'S', 'Purdue', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 251, 'San Francisco 49ers', 'Tatum Bethune', 'LB', 'Florida State', 'ACC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 252, 'Tennessee Titans', 'Jaylen Harrell', 'DE', 'Michigan', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 253, 'Los Angeles Chargers', 'Cornelius Johnson', 'WR', 'Michigan', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 254, 'Los Angeles Rams', 'KT Leveston', 'OG', 'Kansas State', 'Big 12');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 255, 'Green Bay Packers', 'Kalen King', 'CB', 'Penn State', 'Big Ten');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 256, 'Denver Broncos', 'Nick Gargiulo', 'C', 'South Carolina', 'SEC');
insert into D24.selection(Tour, Choix, Équipe, Joueur, Poste, Université, Conférence) values (7, 257, 'New York Jets', 'Jaylen Key', 'S', 'Alabama', 'SEC');
